export default {
    projets: [
        {
          id: "1",
          name: "Ghibli Projet",
          description: "Projet en VUE JS",
          desc: "L'évaluation de notre module de Framework Js était d'utilisé une API et de faire un site qui tri et 'display' les informations. L'API choisis est une REST API sur les films de du studio Ghibli. Le Framework que nous avons utilisé est VUE JS. Avec ce que nous abons vu en cours et des recherches personnelle j'ai réussi à afficher les films ghibli du plus récent au plus ancien et inversement, du mieux noté au moins bien et inversement. Il est possible en plus de rechercher des films avec une bar de recherche qui met à jour les données afficher instantanément et sans bouton de recherche. Les filtres fonctionne avec des boutons qui font appellent à des fonctions. Les card des films sont cliquable et mène aux détails de ces derniers.",
          tag: "Développement",
          date : "20/12/2023",
          titleimg: "https://i.ibb.co/ckqcL3N/ghibli.png",
          image1 : "https://media.vogue.fr/photos/5dc59b122c63420008da9dab/2:3/w_2560%2Cc_limit/010_A7A13245_284.jpg",
          img1:"https://i.ibb.co/J7ck8sK/Capture1.png",
          img2:"https://i.ibb.co/M9KW6nK/Capture2.png",
          img3:"https://i.ibb.co/wdGgztq/Capture3.png",
        },
        {
          id: "2",
          name: "Projet Tri Php",
          description: "Projet pour revoir le PHP et le SQL",
          desc: "Afin de m'améliorer en php et de revoir les bases avant de reprendre les cours j'ai fais avec un amis une base de données en SQL puis nous avons fais une page pour les afficher, les trier et faire des recherches. C'est un petit projet personnelle sur un thème qui nous passionne. Nous aimerions donc pousser ce projet et l'améliorer. ",
          tag: "Développement",
          date : "05/01/2024",
          titleimg: "https://i.ibb.co/wpRLQ2L/php.png",
          image1 : "https://brand.riotgames.com/static/a91000434ed683358004b85c95d43ce0/8a20a/lol-logo.png",
          img1:"https://i.ibb.co/BwpZBV0/Capture.png",
          img2:"https://i.ibb.co/dc0ypph/Capture3.png",
          img3:"https://i.ibb.co/Hd0cWjf/Capture2.png",
        },
        {
          id: "3",
          name: "Partiel B2",
          description: "Site Wordpress",
          desc: "Le projet 'Le Kit Indé' est notre premier projet de partiel de seconde année. Le but était de faire un site et une campagne de communication destinés à des lycéens et tout cela en 1 semaine.",
          tag: "Développement",
          date : "10/12/2023",
          titleimg: "https://i.ibb.co/pnmVGzM/partiel.png",
          image1 : "https://cdn-icons-png.flaticon.com/512/9043/9043010.png",
          img1:"https://i.ibb.co/pRwTHs1/Capture1.png",
          img2:"https://i.ibb.co/Nrxr6cT/Capture2.png",
          img3:"https://i.ibb.co/hmxHx4k/Capture3.png",
        },
        {
          id: "4",
          name: "Site Johnson's Kitchen",
          description: "Site en HTML CSS",
          desc: "Jonhson's Kitchen est un projet réalisé dans le cadre d'un cours d'intégration web. Le but était de faire par groupe de deux un site inspiré de carte de visite fournie par notre professeur. Pour cela nous avions plusieurs heures de cours ainsi que des heures de travail personnelle. Nous avons utilisé du HMTL, du CSS ainsi qu'un peu de JS pour le menu burger. La carte de visite était pour un chef personnelle mais nous avons préferé faire un site de vente d'object de cuisine, car cela nous permetait de remplir les conditions d'évaluation. ",
          tag: "Développement",
          date : "10/10/2023",
          titleimg: "https://i.ibb.co/xXb8w3R/john.png",
          image1 : "https://banner2.cleanpng.com/20190926/qiw/transparent-chef-icon-kitchen-icon-5d8df81fb50cf0.3064095415695851837416.jpg",
          img1:"https://i.ibb.co/5RPTn6w/chef-1.png",
          img2:"https://i.ibb.co/Wcs2H4B/chef-2.png",
          img3:"https://i.ibb.co/yBHs0Dk/chef-3.png",
        },
        {
          id: "5",
          name: "Affiche deuxieme annee",
          description: "Productions en photoshop et illustrator",
          desc: "Voici mes affiches produient en deuxième année avec photoshop et illustrator",
          tag: "Développement",
          date : "01/02/2024",
          titleimg: "https://i.ibb.co/Kq6Nz40/affiche.png",
          image1 : "https://cdn-icons-png.flaticon.com/512/902/902686.png",
          img1:"https://i.ibb.co/Pw8SCcM/Noir-et-blanc-1.png",
          img2:"https://i.ibb.co/WyQnkjR/Baptiste-LEMOINE-MIGAUD-Texte.png",
          img3:"https://i.ibb.co/BygYPxw/Baptiste-LEMOINE-MIGAUD-Hors-cadre2.jpg",
        },
        {
          id: "6",
          name: "Affiche premiere annee",
          description: "Productions en photoshop et illustrator",
          desc: "Voici mes affiches produient en première année avec photoshop et illustrator",
          tag: "Développement",
          date : "01/10/2022",
          titleimg: "https://i.ibb.co/Kq6Nz40/affiche.png",
          image1 : "https://cdn-icons-png.flaticon.com/512/902/902686.png",
          img1:"https://i.ibb.co/m0Q9zsQ/Affiche-Balenciaga-DBZ-1.png",
          img2:"https://i.ibb.co/DfNkZm0/Exercice-Tui-1.png",
          img3:"https://i.ibb.co/mTTv6Vy/Escalade-1.png",
        },
      ]
  };